### ISSUE TITLE
no audio in podcast (player)

### ISSUE THREAD

**Issue by lomeat** [nuxdie/frontendweekend#205]
Last version of Yandex Browser, Windows 10. Dont know how to give more tech information. At SoundCloud all okay.

**Comment by nuxdie** [comment]
Thanks for the bug report, @lomeat! Couldn't reproduce the issue on my setup (VirtualBox, Win10, Yandex browser 18.11.1). Please make sure you have Turbo mode/ Ads blocker turned off. As a workaround, I'm implementing a dedicated "Listen on SC" and "download" links in #207. Hope this helps

![localhost_8000_en_](https://user-images.githubusercontent.com/3918844/51419697-db4ae200-1b8c-11e9-8edb-284e1f5db16c.png)
