### ISSUE TITLE
И ещё какие-то ресурсы не по https загружаются, из-за этого настораживающая иконка в адресной строке

### ISSUE THREAD

**Issue by nuxdie** [nuxdie/frontendweekend#64]
<img width="520" alt="screen shot 2018-12-17 at 10 44 15 am" src="https://user-images.githubusercontent.com/3918844/50079043-d808b300-01e8-11e9-956b-c5733125cab6.png">
<img width="509" alt="screen shot 2018-12-17 at 10 44 30 am" src="https://user-images.githubusercontent.com/3918844/50079047-d9d27680-01e8-11e9-9133-e436a89faa02.png">

**Comment by nuxdie** [comment]
![photo5240468616837704189](https://user-images.githubusercontent.com/3918844/50079081-e787fc00-01e8-11e9-8f7d-e4bcfd67a782.jpg)

**Comment by nuxdie** [comment]
originally reported by @pqr

**Comment by nuxdie** [comment]
this should be fixed now. @pqr please confirm or reopen the issue, thanks for the report!

**Comment by pqr** [comment]
confirm, all correct now
